#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/acore-env.sh"

echo "=========================================="
echo "AzerothCore Complete Setup - All 5 Steps"
echo "=========================================="
echo ""

echo "[STEP 1/5] Installing Required Packages..."
echo ""
echo "Running: $SCRIPT_DIR/install-deps.sh"
"$SCRIPT_DIR/install-deps.sh"
echo ""
echo "✓ STEP 1 Complete"
echo ""

echo "[STEP 2/5] Getting Source Code..."
echo ""
echo "Running: $SCRIPT_DIR/sync-source.sh"
"$SCRIPT_DIR/sync-source.sh"
echo ""
echo "✓ STEP 2 Complete"
echo ""

echo "[STEP 3/5] Building Source Code..."
echo ""
echo "Running: $SCRIPT_DIR/build-azerothcore.sh"
"$SCRIPT_DIR/build-azerothcore.sh"
echo ""
echo "✓ STEP 3 Complete"
echo ""

echo "[STEP 4/5] Setting Up Database..."
echo ""
echo "Running: $SCRIPT_DIR/init-db.sh"
"$SCRIPT_DIR/init-db.sh"
echo ""
echo "✓ STEP 4 Complete"
echo ""

echo "[STEP 5/5] Configuration & Helper Scripts..."
echo ""
echo "Running: $SCRIPT_DIR/configure-azerothcore.sh"
"$SCRIPT_DIR/configure-azerothcore.sh"
echo ""
echo "✓ STEP 5 Complete"
echo ""

echo "=========================================="
echo "✓ ALL 5 STEPS COMPLETE!"
echo "=========================================="
echo ""
echo "Installation Summary:"
echo "  ✓ Step 1: Required packages installed"
echo "  ✓ Step 2: Source code cloned/updated"
echo "  ✓ Step 3: Source code built"
echo "  ✓ Step 4: Database setup complete"
echo "  ✓ Step 5: Configuration & scripts ready"
echo ""
echo "Next steps:"
echo "  1. Extract or download maps:"
echo "     $AC_INSTALL_HELPERS_DIR/extract-maps.sh"
echo ""
echo "  2. Start servers:"
echo "     $AC_INSTALL_HELPERS_DIR/start-servers.sh"
echo ""
echo "  3. Check status:"
echo "     $AC_INSTALL_HELPERS_DIR/status.sh"
